name: Deploy Sleeper Data Lambda

on:
  push:
    branches: [ main ]
  workflow_dispatch:

env:
  AWS_REGION: us-east-1
  TF_VERSION: 1.9.6

permissions:
  id-token: write
  contents: read

jobs:
  build-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.12"

      - name: Package Controller Lambda
        working-directory: src/controller
        run: |
          mkdir -p ../../build/controller
          pip install -r requirements.txt -t .
          zip -r ../../build/controller/controller_lambda.zip .

      - name: Package Chunk Processor Lambda
        working-directory: src/chunk_processor
        run: |
          mkdir -p ../../build/chunk_processor
          pip install -r requirements.txt -t .
          zip -r ../../build/chunk_processor/chunk_processor_lambda.zip .

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          audience: sts.amazonaws.com
          aws-region: ${{ env.AWS_REGION }}
          role-to-assume: ${{ vars.AWS_ROLE_TO_ASSUME }}

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3

      - name: Terraform Init
        working-directory: infra
        run: terraform init

      - name: Terraform Plan
        working-directory: infra
        run: terraform plan

      - name: Terraform Apply
        working-directory: infra
        run: terraform apply -auto-approve

      - name: Upload Controller Lambda to AWS
        run: |
          aws lambda update-function-code \
            --function-name sleeper-controller \
            --zip-file fileb://build/controller/controller_lambda.zip

      - name: Upload Chunk Processor Lambda to AWS
        run: |
          aws lambda update-function-code \
            --function-name sleeper-chunk-processor \
            --zip-file fileb://build/chunk_processor/chunk_processor_lambda.zip
